version: '3'
  services:
    mysql_database:
      build: ./mysql_docker/
      command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      environment:
        - MYSQL_ROOT_PASSWORD="admin"
      restart: always
      ports: 
        - "3306:33060"

    web:
      #image: nginx
      build: ./nginx_docker/
      ports:
        - "8080:80"
      environment:
        - NGINX_HOST=sitio.com
        - NGINX_PORT=80

    flaskapp:
      build: ./api_docker/
      ports:
        - "3000:3000"
      restart: always 
